ecmaFeatures:
    arrowFunctions: true
    binaryLiterals: true
    blockBindings: true
    defaultParams: true
    destructuring: true
    forOf: true
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralDuplicateProperties: true
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    octalLiterals: true
    restParams: true
    spread: true
    templateStrings: true

rules:
    array-bracket-spacing:
        - 1
        - "never"
    brace-style:
        - 1
        - "1tbs"
        - allowSingleLine: true
    semi:
        - 2
        - "never"
    no-duplicate-case: 2
    no-extra-parens: 2
    no-extra-semi: 2
    no-func-assign: 2
    no-inner-declarations: 2
    no-invalid-regexp: 2
    no-irregular-whitespace: 2
    no-unreachable: 2
    no-unused-vars:
        - 2
        - vars: "local"
          args: "after-used"
    valid-typeof: 2
    curly: 2
    eqeqeq:
        - 2
        - "smart"
    no-new: 2
    block-spacing:
        - 1
        - "always"
    comma-spacing:
        - 1
        - before: false
          after: true
    no-trailing-spaces: 1
    no-spaced-func: 1
    no-multiple-empty-lines:
        - 1
        - max: 2
          maxEOF: 1
    key-spacing:
        - 1
        - beforeColon: false
          afterColon: true
    no-mixed-spaces-and-tabs: 1
    space-after-keywords:
        - 1
        - "always"
    jsx-quotes:
        - 2
        - "prefer-single"

environment:
    commonjs: true
